on:
  push:
    branches:
      - main

jobs:
  say-hi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hi Env
        run: echo "Hi, this is my env ${{ github.workflow }}
