name: Print Environment Name

on:
  push:
    branches:
      - main

jobs:
  print-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Environment Name
        run: echo "Environment Name: ${{ github.workflow }}"