name: Deploy to prod

on:
  push:
    branches:
      - main

jobs:
  say-what:
    runs-on: ubuntu-latest

    steps:
      - name: Say What
        run: echo "Say what...?"

  deploy-prd:
    #needs: print-env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Prod stuff
        run: echo "Print some prod stuff..."